### ISSUE TITLE
get-pip.py seems to fail on Cygwin

### ISSUE THREAD

**Issue by jdemeyer** [sagemath/cysignals#105]
See [AppVeyor log](https://ci.appveyor.com/project/sagemath/cysignals/builds/22315257).

CC @embray

**Comment by embray** [comment]
Although something like this felt vaguely familiar, I had to re-convince myself it's actually as bad as it looks: If an application run by powershell writes something to stderr it detects this and wraps that output in and raises a `NativeCommandError`, thus technically returning an error.

In other words, it assumes nobody will abuse `stderr` to write messages that are not *actually* error messages representing an unrecoverable error condition; it has no concept of how unix programs often use stderr to write any kinds of out-of-band messages, besides strictly errors.  Who's right? I don't know.  But this has to be worked around.  I definitely recall dealing with this at some previous time.
