### ISSUE TITLE
Lack of details in error message from sigdie_for_sig with inside=1

### ISSUE THREAD

**Issue by embray** [sagemath/cysignals#110]
In reference to https://groups.google.com/d/msg/sage-support/kGmFy4lSUv0/35LFAjFGCQAJ

It occurs to me that in `sigdie_for_sig` if `inside=1` it just calls `sigdie` with the error message `"An error occurred during signal handling."`.

However, we still got here due to a signal that occurred during signal handling (e.g. a SIGSEGV) and it would be somewhat helpful to at least know what that was.  I know it will still turn up in the exit code, but that's hard to get from, say, a user making a bug report.

**Comment by jdemeyer** [comment]
There was never a need to further debug this since it shouldn't occur in normal usage. But I agree that #108 is a good guess.

**Comment by embray** [comment]
"it shouldn't occur in normal usage" is quite optimistic though :) As well-tested and carefully crafted as cysignals is it still would be useful to get a better message here, especially as we move into trickier waters like better threading support.

**Comment by embray** [comment]
Closed by a8a8ad78 apparently.
