### ISSUE TITLE
Release management and testing

### ISSUE THREAD

**Issue by jdemeyer** [sagemath/cysignals#12]
We should think about release management and testing.

Making a package should be easy (`./setup.py sdist`) but somebody needs to take care of pull requests. Who will have write access to the repo?

Concerning testing: this package sits very close to the operating system, so you would expect OS-specific issues. So really, we should try to test this on a range of operating systems.

**Comment by malb** [comment]
Every commit is automatically tested on [travis-ci]( https://travis-ci.org/malb/signal.pyx). We're also checking for lenient PEP8 compliance ` flake8 --max-line-length=120 --max-complexity=16 --ignore=E22,E241,E731 src`

For OS variety, this code is supposed to go into Sage where it would be tested just as it is now.

**Comment by kcrisman** [comment]
I don't know if that link only works for project members but I got

> The repository at malb/signal.pyx was not found.

**Comment by kiwifb** [comment]
That may because the repo moved. I thought github was handling those moves better.

**Comment by malb** [comment]
Github does, but Travis does not apparently. I've rewritten history and fixed the link :)

**Comment by jdemeyer** [comment]
Related to #22: we should test on Python 3 too.

**Comment by jdemeyer** [comment]
I think this can be closed now, things have been sorted out.
