### ISSUE TITLE
Release 1.10.3

### ISSUE THREAD

**Issue by embray** [sagemath/cysignals#131]
I would like to make a version 1.10.3 release of Cysignals.  It will contain some recent and upcoming bug fixes, but notably *not* the assembly longjmp implementation, which should at a minimum necessitate a new minor release since it's a big addition (and currently does not work for me in Sage, but that's another story).

@jdemeyer I haven't seen you around in a while and I don't know if you're monitoring this repo.  I hope you're doing okay =)  I can make the release if you don't mind, but I don't have access to the PyPI project.

**Comment by embray** [comment]
@vdelecroix I see you also are a maintainer of cysignals on PyPI if you can help with that in case Jeroen is unavailable.

**Comment by embray** [comment]
@videlec I see you also are a maintainer of cysignals on PyPI if you can help with that in case Jeroen is unavailable.

**Comment by videlec** [comment]
Hi @embray. Indeed, at the time Jeroen granted me access to cypari2 it did the same with cysignals. Let me do that now.

**Comment by videlec** [comment]
@embray Sadly, I don't seem to be able to modify any permissions here. Let me contact Jeroen again by e-mail (I will cc you).

**Comment by videlec** [comment]
@embray Sorry it is only on PyPI that you want access... I can do that!

**Comment by embray** [comment]
@videlec Thanks!  Yeah, I have admin on the github project, just not on PyPI.

**Comment by embray** [comment]
Ok, it's working now, thank you!

**Comment by kliem** [comment]
Please wait with the release. There are some problem with #128, which I hopefully fixed in #134.

I'm currently investigating. Once I figured out what is going on, I will open an issue or whatever necessary. I think today still.

**Comment by embray** [comment]
Finally the CI for the 1.10.x branch is working again too.  I'm pretty confident to make this release pending a positive review on https://trac.sagemath.org/ticket/31474#comment:7

**Comment by embray** [comment]
Complete: https://pypi.org/project/cysignals/1.10.3/
