### ISSUE TITLE
Installing headers

### ISSUE THREAD

**Issue by malb** [sagemath/cysignals#15]
Installing headers seems to present a problem.

Let's assume:

```python
headers = ["src/cysignals/struct_signals.h",
           "src/cysignals/debug.h",
           "src/cysignals/macros.h",
           "src/cysignals/pxi.h",
           "build/src/cysignals/signals_api.h",
           "build/src/cysignals/signals.h"]
```

## headers

We could use `setup(headers=headers)` as intended. However, because of pypa/virtualenv#510 this will fail in virtualenvs, e.g. on travis-ci.

## package_data

We could try `setup(package_data={"cysignals": ["signals.pxi", "signals.pxd"] + headers}` but this will fail because the arguments to `package_data` must relative to the source directory of said module. We switched to cythonizing in the build directory rather than the source directory in 338d8e433a3b3ecaeed46c7c1925c98d45ff3762 which means some of our headers are not in the source directory. 

## data_files

We could try `setup(data_files = [(os.path.join(sys.prefix, "include"), headers)])` but that produces problems for distributions as pointed out by @kiwifb at 89dc7a7235acf9f5a7a4b4b37b68b15d0c0d350f

**Comment by malb** [comment]
To me, the cleanest solution I see is to cythonize in the source directory and to use `package_data`. We'd then have to write some documentation advising package authors how to link in cysignals.

**Comment by jdemeyer** [comment]
I have an almost-working solution which assumes
https://github.com/cython/cython/pull/483

Hang on...
