### ISSUE TITLE
Publish wheels to pypi

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/cysignals#153]
In order to make it easier to use cysignals, it would be nice if pre-built wheels are published to pypi.

**Comment by kliem** [comment]
This somewhat depends on #125. At least it makes sense to tackle it afterwards, because it removes the optional build-time dependency.

Everything else is system dependent, which is fine for a wheels, I believe.

**Comment by dimpase** [comment]
see #158 - it should be just it.

**Comment by dimpase** [comment]
well - there will be a manual step of downloading the artefact and uploading the wheels there to PyPI using twine, but, OK, this is minor.
