### ISSUE TITLE
Release 1.11.0

### ISSUE THREAD

**Issue by kliem** [sagemath/cysignals#157]
What is missing yet?

Is this good to go for now?

**Comment by mkoeppe** [comment]
What about the failure on `ubuntu-trusty`? https://github.com/sagemath/cysignals/runs/4318488186?check_suite_focus=true

**Comment by mkoeppe** [comment]
Oh, I see that's #155

**Comment by kliem** [comment]
I don't think I will be able to solve #155 for this release. I also don't think is got introduced recently.
It's probably related to not using system installed python (also happens in other cases, were system python is rejected).

**Comment by mkoeppe** [comment]
Then I think it's fine to make a release.

**Comment by kliem** [comment]
@embray, @videlec

Can one of you please push this release to pypi. I'm gathering that you have permission as you are listed as maintainers.
