### ISSUE TITLE
Segmentation fault on raspi model B

### ISSUE THREAD

**Issue by elijahlimas123** [sagemath/cysignals#165]
i have git cloned into https://github.com/cyphunk/JTAGenum.git. i cd into JTAGenum and run sudo bash JTAGenum.sh. this returns with Segmentation fault. prior to getting this error it was telling me that i was missing parentheses in the print statements in the .sh file, i fixed that and now running JTAGenum.sh gives me Segmentation fault.

i am on raspberry pi model B

**Comment by kliem** [comment]
I'm confused. Is this a problem with `cysignals`?

**Comment by kliem** [comment]
I suppose this has nothing to do with `cysignals`.
