### ISSUE TITLE
Submit to PyPI

### ISSUE THREAD

**Issue by malb** [sagemath/cysignals#19]
After version 1.0 we should submit this package to [PyPI](https://pypi.python.org/pypi).

**Comment by jdemeyer** [comment]
When it works in Sage, yes.

**Comment by malb** [comment]
+1

**Comment by jdemeyer** [comment]
When registering on PyPI, I have to agree to the following terms:

> By registering to upload content to PyPI, I agree and affirmatively acknowledge the following:

> [...]
> The PSF is free to use or disseminate any content that I upload on an unrestricted basis for any purpose. In particular, the PSF and all other users of the web site are granted an irrevocable, worldwide, royalty-free, nonexclusive license to reproduce, distribute, transmit, display, perform, and publish the content, including in digital form.
> [...]

Isn't this contradicting the LGPL?

**Comment by malb** [comment]
I can't see a contradiction, they get to distribute it etc, which sounds alright with the (L)GPL

**Comment by jdemeyer** [comment]
I see. I guess this is compatible with clause 4 of the (L)GPL:

> You may convey verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice; keep intact all notices stating that this License and any non-permissive terms added in accord with section 7 apply to the code; keep intact all notices of the absence of any warranty; and give all recipients a copy of this License along with the Program.

You may charge any price or no price for each copy that you convey, and you may offer support or warranty protection for a fee.

**Comment by jdemeyer** [comment]
Done at https://pypi.python.org/pypi/cysignals/1.0
