### ISSUE TITLE
Provide a `get_include` function?

### ISSUE THREAD

**Issue by jvkersch** [sagemath/cysignals#25]
First of all, thanks for this extremely useful module! Just being able to properly handle Ctrl-C in my ill-behaving Cython modules has shaved a considerable amount of time off my debugging cycle.

I read the remark in the docs about having to add `sys.path` to the include dirs when using this in a project, and due to some project-specific build oddities I couldn't get this to work right away. Would it make sense to have a function `cysignals.get_include()` (in analogy with a function of the same name in numpy) that returned the relevant include dirs? Something like
```python
def get_include():
    import cysignals
    return os.path.join(os.path.dirname(cysignals.__file__), 'include')
```

Also, am I correct in thinking that `python setup.py develop` doesn't work for Cysignals?

**Comment by jdemeyer** [comment]
You are probably confusing the include_**path** from Cython with the include_**dirs** from distutils. I know it's confusing, but the first is how Cython looks for `.pxi` and `.pxd` files and the second is how distutils looks for `.h` files when compiling the sources.

You need `sys.path` in the include_**path** which will then use Cython machinery to automatically add the correct include_**dirs**.

I do realize now that this only works properly if the `ext_modules` are generated by Cython. In other words, if `setup.py` looks like
```
setup(...,
    ext_modules=cythonize(...)
)
```
If this is not the case, you indeed need to manually add `include_dirs`. We could provide a function like the one you describe, although I would consider that "unsupported".

**Comment by jdemeyer** [comment]
> Also, am I correct in thinking that python setup.py develop doesn't work for Cysignals?

I have no experience with `python setup.py develop`. But from what I understand, it seems that it can never really work well for Cython modules. You need some mechanism to run Cython and distutils whenever the Cython sources change.

**Comment by jvkersch** [comment]
Thanks for the clarification, Jeroen, I'm indeed in the situation where my extension modules are not generated by Cython. And I didn't know about the distinction between `include_{path, dirs}`, that clears things up, thanks!

I agree `python setup.py develop` is not as useful for Cython modules as it is for pure Python modules (for the reason that you indicate). I was just curious, since it is generally the first thing I try to do when installing a package from GitHub.
