### ISSUE TITLE
Stub implementation for Windows?

### ISSUE THREAD

**Issue by anntzer** [sagemath/cysignals#30]
Due to a bug on Cython's include resolution(?), it is not possible to conditionally include cysignals depending on the OS: see https://groups.google.com/d/topic/cython-users/E9_hATlRhII/discussion

I wonder whether the devs of cysignals would agree to provide a stub version of cysignals for Windows, where all functions are simply do-nothing: from my point of view, the ability to handle signals is mostly a convenience to the user (albeit a hugely helpful one) and rarely carries semantic weight; however, providing such stubs would make the use of a single code base across OSes much easier.  A quick skimming of the docs suggested that the only function that would behave seriously differently is `alert`, which could e.g. immediately raise a RuntimeError on Windows.  (As a side note, a list of all available functions would be nice for the docs).

Hopefully Cython will fix this issue and the stubs can then be removed...

**Comment by jdemeyer** [comment]
I think it's easy to fix the dependency issue in Cython. I already fixed a similar bug once, let me look at that.

**Comment by jdemeyer** [comment]
Does https://github.com/cython/cython/pull/510 fix your problem? Would that be sufficient to close this issue?

**Comment by anntzer** [comment]
I guess this could be enough, but will remain an issue until the next release of Cython (assuming that the PR gets merged...), which may take a while.  So, a stub would still be helpful as a temporary solution.

**Comment by jdemeyer** [comment]
Personally, I consider this issue to be fixed with the Cython patch. So I do not plan to provide a stub implementation.

**Comment by anntzer** [comment]
OK, feel free to close this then.

**Comment by anntzer** [comment]
Actually, even with the upstream patch it remains slightly tricky to write cross-platform code because each call to `sig_check` needs to be protected by a SYS_UNAME guard.  So I'll reiterate the request for a Windows stub.

**Comment by jdemeyer** [comment]
It seems that the CyPari people have ported cysignals (or at least some parts) to Windows:

https://bitbucket.org/t3m/cypari

**Comment by jdemeyer** [comment]
We are trying to actually port (parts of) cysignals to Windows: #76
