### ISSUE TITLE
building either with or without PARI support: quid module approach ?

### ISSUE THREAD

**Issue by jgmbenoit** [sagemath/cysignals#33]
I could build cysignals without PARI (I added material in configure.ac and setup.py to allow a clean building: I will certainly pull request once it is plainly ready). On the other hand, I have not built it against PARI. Nevertheless, as Debian packager, I considering to provide one debball without PARI support and one debball with PARI support. From the outside this makes sense, I guess. On the other hand, given that the code related to the PARI support is rather tiny (and because I suspect that other PARI like stuff could be also integrated), I am wondering if a module/plugin machinery might be implemented instead. I see how to do it in C, but I am not familiar enough with [p|c]ython to know whether or not it can be done easily (but I can hardly think that it cannot). From a distribution (as Debian) point of view, this is a far more pertinent approach: one debball for the cysignals core, and debballs for the modules/plugins (PARI and alikes). From an upstream point of view, it enlarges potential usages.
Please let me know what you think. Thanks, Jerome

**Comment by jdemeyer** [comment]
> I am wondering if a module/plugin machinery might be implemented instead.

I don't immediately see a simple way to do this. Keep in mind 2 things:

1. Efficiency is very important for `cysignals`. Luckily, the interaction with PARI happens in non-critical code.

2. Portability to POSIX systems is also very important. It should work on other operating systems besides Linux.

**Comment by jgmbenoit** [comment]
I am fully agree with points 1 and 2.
Through my C oriented mind, I have in mind a [DL machinery](http://tldp.org/HOWTO/Program-Library-HOWTO/dl-libraries.html)

**Comment by jdemeyer** [comment]
How does Debian in general handle packages with optional dependencies?

**Comment by jdemeyer** [comment]
I don't think that it's the duty of cysignals to solve the issues of distributions.

**Comment by jgmbenoit** [comment]
I do not think it is a distribution issue: any potential user may want to install cysignals with or without PARI support.

**Comment by jdemeyer** [comment]
> I do not think it is a distribution issue: any potential user may want to install cysignals with or without PARI support.

OK, sure. But adding a "module approach" to deal with it at runtime is a distribution issue. I think that most users would be happy to specify this at `configure`-time.

**Comment by jgmbenoit** [comment]
It was a suggestion. For packaging, the choice occurs at configure time, so as most users, I would be happy to specify it at configure  time.

**Comment by jdemeyer** [comment]
In that case, I totally misunderstood you...

**Comment by kiwifb** [comment]
I must say that conversation started some trains of thoughts here: Why does cysignals needs pari in the first place? If there are pieces that are pari specific couldn't they be moved (now that we have it) to cypari?

**Comment by jdemeyer** [comment]
> Why does cysignals needs pari in the first place?

See https://trac.sagemath.org/ticket/18919
