### ISSUE TITLE
Any good reason to externalize the helper script ?

### ISSUE THREAD

**Issue by jgmbenoit** [sagemath/cysignals#34]
In other words, is it possible to integrate the helper  cysignals-CSI-helper.py script  into the main script cysignals-CSI ? The rational behind my question is that cysignals-CSI-helper.py is currently installed in PREFIX/bin , which the right place for the main script but not for the helper one.

**Comment by jdemeyer** [comment]
Everything is possible, which doesn't mean that it's a good idea. Maybe we should just install the helper script in a different place? It is not meant to be executed directly, it is more like a data file.

**Comment by jgmbenoit** [comment]
Let say that we can put it in an other place, for instance where the rest of the material is put. The issue is then how to grab the helper script.

**Comment by jgmbenoit** [comment]
Is putting the helper script in PREFIX/share/cysignals is fine with ?

**Comment by jgmbenoit** [comment]
This solution seems not fit very well with the setup.py machinery, so I suspect it is too U*NIX oriented.
I am on my way to figure out something that fit better.

**Comment by jgmbenoit** [comment]
I am beginning to think that dealing with one script is by far the best option.

**Comment by jgmbenoit** [comment]
Finally I figured out a solution that fits the setup.py machinery. I will pull a request soon.

**Comment by jgmbenoit** [comment]
I have just pulled the request, so I am going to close this issue. Thanks for your comment.
