### ISSUE TITLE
Does CSI stand for Crime Scene Investigation ?

### ISSUE THREAD

**Issue by jgmbenoit** [sagemath/cysignals#35]
or is it some [C|P]ython jargon ?

**Comment by jdemeyer** [comment]
@vbraun

**Comment by jgmbenoit** [comment]
CySIgnals

**Comment by jgmbenoit** [comment]
Nevertheless, I thinks that Crime Scene Investigation is quite appropriate here :-)
I am closing the issue.

**Comment by vbraun** [comment]
That was the inspiration, indeed. 

I'm not opposed to renaming it, though. Its better to be explicit than funny...
