### ISSUE TITLE
debug.h is not installed

### ISSUE THREAD

**Issue by antonio-rojas** [sagemath/cysignals#42]
The debug.h header is not installed by setup.py, yet it is included from struct_signals.h. This prevents compiling anything against cysignals 1.3:

```
 In file included from build/src/fpylll/fplll/integer_matrix.cpp:468:0:
/usr/lib/python2.7/site-packages/cysignals/struct_signals.h:27:19: fatal error: debug.h: No such file or directory
 #include "debug.h"
                   ^
compilation terminated.
```

**Comment by kiwifb** [comment]
Looks present to me in 1.3.2, in the same folder as `struct_signals.h`.

**Comment by jdemeyer** [comment]
Also in the [Travis build log](https://travis-ci.org/sagemath/cysignals/jobs/174215195#L683), I see
```
copying build/lib.linux-x86_64-2.7/cysignals/debug.h -> /home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/cysignals
```

**Comment by antonio-rojas** [comment]
Ah right, this is caused by using the --skip-build flag.
