### ISSUE TITLE
Incorrect path in __init__.pxd after --user install

### ISSUE THREAD

**Issue by anntzer** [sagemath/cysignals#44]
After `pip install --user cysignals`, `cysignals/__init__.pxd` will contain the line `#disutils: include_dirs = /path/to/master/pythonX.Y/site-packages/cysignals`, rather than pointing to `~/.local/lib/pythonX.Y/site-packages/cysignals`.

I believe this is because pip first creates a wheel from the package, so there's no way, at that time, to know where the package will end up being installed.

**Comment by kiwifb** [comment]
If that's the case it is very poorly thought. I am more wondering if the `__init__.pxd` file should be produced during the install phase rather than the `build_ext` phase as it is now.

**Comment by anntzer** [comment]
Couldn't the headers (not the pxi) just be installed as data_files into `/path/to/include/python3.5m/cysignals/`?  This directory would then get picked up by default.

The discussion at https://github.com/pybind/pybind11/pull/350 convinced me that this is the simplest way to go.

**Comment by jdemeyer** [comment]
> This directory would then get picked up by default.

I don't see why...

**Comment by jdemeyer** [comment]
Sorry, but this works for me. What are the *exact* steps to reproduce?

**Comment by anntzer** [comment]
>> This directory would then get picked up by default.

> I don't see why...

I was going to say, it is in the default include path:
```
$ python-config --includes
-I/usr/include/python3.5m -I/usr/include/python3.5m
```
but actually that's not true of for the --user install location.  So I was wrong, that won't work either...

> Sorry, but this works for me. What are the exact steps to reproduce?

Make sure you don't have /etc/pip.conf or ~/.config/pip/pip.conf or a config file anywhere else (https://pip.pypa.io/en/stable/user_guide/#config-file); also make sure that you don't have any `PIP_*` environment variables set (https://pip.pypa.io/en/stable/user_guide/#environment-variables).

Empty your pip cache (`rm -rf ~/.pip/cache`).

My python version is 3.5.2 (latest), pip version is 9.0.1 (latest).  Then, run:
```
$ pip install --user --ignore-installed --upgrade cysignals
```
`--ignore-installed` makes a user install even if you already have a system-wide install.  `--upgrade` forces a reinstall.  Then:
```
$ cat ~/.local/lib/python3.5/site-packages/cysignals/__init__.pxd                            
# distutils: include_dirs = /usr/lib/python3.5/site-packages/cysignals
# distutils: extra_link_args = -lpari
```
Note the incorrect include_dirs path.

**Comment by jdemeyer** [comment]
Works for me with pip-7.1.2 (with Python 2.7 and Python 3.4)...
```
$ cat ~/.local/lib64/python2.7/site-packages/cysignals/__init__.pxd
# distutils: include_dirs = /home/jdemeyer/.local/lib64/python2.7/site-packages/cysignals
# distutils: extra_link_args = 

$ cat ~/.local/lib64/python3.4/site-packages/cysignals/__init__.pxd
# distutils: include_dirs = /home/jdemeyer/.local/lib64/python3.4/site-packages/cysignals
# distutils: extra_link_args = 
```

**Comment by jdemeyer** [comment]
Also works for me with `pip 9.0.1 from /home/jdemeyer/.local/lib64/python3.4/site-packages (python 3.4)`

**Comment by jdemeyer** [comment]
Maybe I should mention
```
Python 3.4.1 (default, Sep  4 2015, 12:50:14) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__
'18.4'
```

**Comment by anntzer** [comment]
Even with setuptools 18.4 and pip 9.0.1 I have the same issue.
I have tried both on Arch Linux with the system-wide Python install, and on Ubuntu with a conda Python.

**Comment by jdemeyer** [comment]
And I tried system-wide Python and SageMath's Python. In both cases it worked.

**Comment by antonio-rojas** [comment]
This also affects installs done with 'python setup.py install --root=foo'. The include path in the generated __init__.pxd contains the full path, including --root. This breaks distro packaging of cysignals >=1.3, the resulting packages need to be patched. It worked correctly in 1.2.

This doesn't happen if one does separate build and install steps, with 'python setup.py build' and 'python setup.py install --skip-build -root=foo'. But in that case the installed package is missing the generated .h files (issue #42)

**Comment by kiwifb** [comment]
correct
```
fbissey@QCD-nzi3 ~ $ eix cysignals
[I] dev-python/cysignals [1]
     Available versions:  ~1.1.1-r1 (~)1.3.2-r1 **9999 {PYTHON_TARGETS="python2_7 python3_4 python3_5"}
     Installed versions:  1.3.2-r1(13:24:19 18/11/16)(PYTHON_TARGETS="python2_7 python3_4 -python3_5")
     Homepage:            https://github.com/sagemath/cysignals
     Description:         interrupt and signal handling for Cython

[1] "sage-on-gentoo" /var/lib/layman/sage-on-gentoo
fbissey@QCD-nzi3 ~ $ more /usr/lib64/python2.7/site-packages/cysignals/__init__.pxd
# distutils: include_dirs = /scratch2/portage/dev-python/cysignals-1.3.2-r1/image/_python2.7/usr/lib64/python2.7/site-packages/cysignals
# distutils: extra_link_args = -lpari
fbissey@QCD-nzi3 ~ $ more /usr/lib64/python3.4/site-packages/cysignals/__init__.pxd
# distutils: include_dirs = /scratch2/portage/dev-python/cysignals-1.3.2-r1/image/_python3.4/usr/lib64/python3.4/site-packages/cysignals
# distutils: extra_link_args = -lpari
```

**Comment by jdemeyer** [comment]
OK, the `--root` issue is clear.

**Comment by jdemeyer** [comment]
Does #45 fix the `--root` problem?

**Comment by jdemeyer** [comment]
I updated #45 to also check the `--user` option. For those people with a broken `--user`: please test #45 and post the result of running `make check-user`.

**Comment by anntzer** [comment]
FWIW I have an apparently separate failure:
```
<elided>
export PYTHONUSERBASE="`pwd`/user" && python -B rundoctests.py src/cysignals/*.pyx
Doctesting 4 files.
src/cysignals/alarm.pyx
src/cysignals/pselect.pyx
**********************************************************************
File "src/cysignals/pselect.pyx", line 243, in pselect.pyx
Failed example:
    (0.2 <= t <= 0.9) or t
Expected:
    True
Got:
    1.0029985904693604
**********************************************************************
1 items had failures:
   1 of  69 in pselect.pyx
***Test Failed*** 1 failures.
src/cysignals/signals.pyx
src/cysignals/tests.pyx
make: *** [Makefile:97: check-user-doctest] Error 1
```

**Comment by jdemeyer** [comment]
Is it reproducible? That error could happen if the machine is under very high load.

**Comment by antonio-rojas** [comment]
All is fine wrt --root with #45

**Comment by anntzer** [comment]
The pselect test consistently fails for me.  I've tried under two Arch boxes (distro-packaged Python) and in an Ubuntu box (miniconda Python).

As a side note, `make check-user` also fails when Cython is itself installed as `--user` as the setting of `PYTHONUSERBASE` then prevents python from importing Cython.

**Comment by jdemeyer** [comment]
> As a side note, make check-user also fails when Cython is itself installed as --user as the setting of PYTHONUSERBASE then prevents python from importing Cython.

I don't think there is much I can do that about that. I would prefer to keep the test anyway, even if it fails for Cython user installs.

**Comment by jdemeyer** [comment]
> The pselect test consistently fails for me. I've tried under two Arch boxes (distro-packaged Python) and in an Ubuntu box (miniconda Python).

That's bad. Unfortunately, I cannot reproduce it.

**Comment by jdemeyer** [comment]
You should create a new issue for the failing `pselect` test.

**Comment by jdemeyer** [comment]
> The pselect test consistently fails for me.

Good news, it reproduced this on Python 3.5 (I added that version to Travis CI). This is almost certainly due to https://www.python.org/dev/peps/pep-0475/

**Comment by jdemeyer** [comment]
I added two commits. The first one fixes the Python 3.5 issue, the second one makes a lot of changes to the installation process (including fixing `--root`).

Please try again with current master. If this doesn't fix your original issue, I'm afraid there is nothing more I can do since I cannot reproduce it.

**Comment by anntzer** [comment]
Actually master fixes both the --user install for me and the interrupt issue.  Thanks for your quick reply!

**Comment by kiwifb** [comment]
I think that stuff is important enough to warrant a minor release.

**Comment by jdemeyer** [comment]
> Actually master fixes both the --user install for me

I don't understand why though...

**Comment by jdemeyer** [comment]
> I think that stuff is important enough to warrant a minor release.

Done!

**Comment by kiwifb** [comment]
I receive notifications for those :) will be bumping things in sage-on-gentoo overlay shortly.
