### ISSUE TITLE
Totally broken in sage shell, no diagnostic printed

### ISSUE THREAD

**Issue by vbraun** [sagemath/cysignals#48]
The created file is empty for the record:
~~~~
(sage-sh) vbraun@volker:sage$ ./local/bin/cysignals-CSI -p 14951
Attaching gdb to process id 14951.

Saved trace to /home/vbraun/.sage/crash_logs/crash_OjYVTk.log
~~~~
It would be nice to actually check the return code from gdb, which is non-zero.

What breaks gdb is of course LD_PRELOADing libpython2.7, where gdb uses libpython3 for quite a while now. Is there anybody still using an old gdb with python2? 

IMHO the hashbang should just point to python3.

There are still a couple number of python3 incompatibilites in the script.

**Comment by jdemeyer** [comment]
> What breaks gdb is of course LD_PRELOADing libpython2.7, where gdb uses libpython3 for quite a while now.

Well, `gdb` needs to be compiled against the "correct" version of Python for this to work. I doubt that you can use a gdb-compiled-with-Py3 to debug Py2 code. Unless I am misunderstanding something...

Within Sage, I usually install the `gdb` package within Sage. Then this problem does not occur.

**Comment by jdemeyer** [comment]
> It would be nice to actually check the return code from gdb, which is non-zero.

Fixed in https://github.com/sagemath/cysignals/commit/e2d2aac319307fcbc8df23e7e834ec7d5c97a2fe

**Comment by jdemeyer** [comment]
> There are still a couple number of python3 incompatibilites in the script.

Right. I'm currently adding a unittest for `gdb`. Hang on...

**Comment by vbraun** [comment]
At least you can use gdb-py3 to debug py2 on the C level without LD_PRELOAD. But if the LD_PRELOAD doesn't match what gdb is using then gdb just won't start and you can't do anything. What can we possibly gain from setting LD_PRELOAD?

**Comment by jdemeyer** [comment]
> What can we possibly gain from setting LD_PRELOAD?

You could ask the author of https://github.com/sagemath/sage/commit/11d05b20225e32e6e68d7bf1aff0aa47e3deb0de :-)

Unfortunately, I cannot get the gdb debugging to work on Python >= 3.3 anyway due to https://github.com/cython/cython/issues/1655 (see #52)

**Comment by vbraun** [comment]
Yes I wrote that but it was ages ago... I think it was because back then Sage used LD_LIBRARY_PATH which royally screwed every external program. But now thats out so RPATH can work if we let it...

**Comment by vbraun** [comment]
I made #58 to remove it...
