### ISSUE TITLE
Detect if PARI is present.

### ISSUE THREAD

**Issue by malb** [sagemath/cysignals#6]
Detect if PARI is present in setup.py  and will set flags accordingly.

**Comment by jdemeyer** [comment]
I think that we'll need `autoconf` sooner or later anyway. We might as well do the PARI check there.

**Comment by kiwifb** [comment]
`autoconf` usually makes it harder to install with several versions of `python` concurrently. May need to check exactly what we ship and how we ship it.

**Comment by jdemeyer** [comment]
> autoconf usually makes it harder to install with several versions of python concurrently.

I don't see why. The "autoconf" part of this package wouldn't need to check anything Python-related. It would only check whether certain header files, functions and libraries exist.

**Comment by kiwifb** [comment]
May work.

**Comment by malb** [comment]
Another option is just to enable the user to pass the right options manually. This would work for Sage, which could just set things up appropriately. 

This would avoid the added complexity of autotools. For example, it's bad style to check in `configure` but not everybody has `autoconf` installed.

**Comment by jdemeyer** [comment]
> This would avoid the added complexity of autotools.

I don't want to avoid autotools. There are several hacks currently in the code which could be made cleaner with autotools. I want to add new features which will require `configure` checks.

Note that we could run `./configure` from the `setup.py` script to make the install easier.

> For example, it's bad style to check in `configure` but not everybody has `autoconf` installed.

Note that only *developers* of this package will need `autoconf` installed. And all 3 of them probably have `autoconf` installed already.

**Comment by malb** [comment]
This would prevent `pip install git+https://github.com:malb/signal.pyx.git` for users without `autoconf`. But if we submit it to PyPI that's perhaps not so important.
