### ISSUE TITLE
 rundoctests.py fails when python is not present (but python3 is) 

### ISSUE THREAD

**Issue by jgmbenoit** [sagemath/cysignals#66]
It appears that rundoctests.py in an environment where only python 3 is present and when the executable python is not:
this situation is the current one for Debian SId when only python 3 material is installed.
A quick glance reveals that Open ('python',....)  cannot be honoured.

**Comment by jdemeyer** [comment]
Don't run `./rundoctests.py` when you want to use a specific Pyhton environment. Use `$PYTHON rundoctests.py` instead.

**Comment by jgmbenoit** [comment]
It appeared not enough because the Open('python', ....) in the tests look for 'python' which is not present (or might point to the wrong python). I finally fixed the issue by adding a bin directory in PATH with a 'python' link in it, see [Debian source](https://sources.debian.org/src/cysignals/1.6.6+ds-2/debian/tests/check/).

**Comment by jdemeyer** [comment]
> Open('python', ....)

What do you mean with `Open`?

**Comment by jgmbenoit** [comment]
Sorry, I did not realized that I was corrected: I mean the Popen(['python', ...) that are encoded in src/cysignals/tests.pyx and src/cysignals/pselect.pyx .

**Comment by jdemeyer** [comment]
OK, fixed in master.
