### ISSUE TITLE
make check fails on OSX with Python 3

### ISSUE THREAD

**Issue by saraedum** [sagemath/cysignals#71]
With the latest 1.6.8 release, I am getting the following error on OSX with Python 3
```
Traceback (most recent call last):
  File "rundoctests.py", line 30, in <module>
    resource.setrlimit(resource.RLIMIT_STACK, (stacksize, stacksize))
ValueError: current limit exceeds maximum limit
```
the full log can be found here: https://travis-ci.org/conda-forge/cysignals-feedstock/jobs/350808690#L585

**Comment by jdemeyer** [comment]
To be clear: do you mean **only** with Python 3? Or is it just that you happen to use Python 3?

**Comment by saraedum** [comment]
It works with Python 2.7. But fails with 3.5 and 3.6.

**Comment by saraedum** [comment]
It works fine on Linux with all three.

**Comment by jdemeyer** [comment]
> It works with Python 2.7. But fails with 3.5 and 3.6.

Are you running the tests for Py2 and Py3 in a substantially different way? Are you using different scripts, a different environment, a different machine for those tests?

**Comment by jdemeyer** [comment]
Is it possible to see the output of `ulimit -a` before running the tests (both on Py2 and Py3)?

**Comment by jdemeyer** [comment]
In any case, the proper fix is probably to just ignore the `ValueError`. I'm just asking you those questions to confirm that.

**Comment by saraedum** [comment]
The tests run on TravisCI. The machines should be virtually identical and the environment should be identical except for the versions of Python. The script is certainly the same. I'll add `ulimit -a` and report back.

**Comment by saraedum** [comment]
This is for the Python 2.7 build:
```
+ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
```

And this is the Python 3.5 build
```
+ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
```

**Comment by jdemeyer** [comment]
So those limits are identical... and they are reasonable.

Can I see the script that you use for testing, including the `ulimit -a` calls?

**Comment by saraedum** [comment]
```
ulimit -a
make build
make install
make test
```

**Comment by saraedum** [comment]
This is within a conda environment, which is defined by:
```
requirements:
  build:
    - python
    - setuptools
    - cython
    - pip
    - toolchain
    - pari
```

**Comment by jdemeyer** [comment]
I see that you are just showing the `ulimit -a` at the very beginning of the build. I would like to see the values right at the point that you are running the tests because they might be different (i.e. within the `Makefile` if you use a `Makefile` to run the tests).

**Comment by jdemeyer** [comment]
Also `make --version` in case it matters.

**Comment by saraedum** [comment]
We use cysignal's Makefile and we do not patch anything. I can try to patch the ulimit into the Makefile, one second.

**Comment by saraedum** [comment]
So, inside the Makefile, the limits are lower:
```
export PYTHONPATH="`pwd`/tmp/site-packages" && ulimit -a && python -B rundoctests.py src/cysignals/*.pyx
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 65532
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
Doctesting 5 files.
```
But they are again identical.
`make` is `GNU Make 3.81` for both.

**Comment by jdemeyer** [comment]
Thanks for the info. It still does not explain what is happening...

Sorry for the trouble, but could you do the test again, showing the output of both `ulimit -H -a` and `ulimit -S -a`.

**Comment by jdemeyer** [comment]
Never mind

**Comment by jdemeyer** [comment]
I just reproduced the problem in a plain Python 3 session on OS X:
```
bash-3.2$ ( ulimit -s hard; ./sage --python3 -c 'import resource; stacksize = 1 << 20; resource.setrlimit(resource.RLIMIT_STACK, (stacksize, stacksize))' )
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: current limit exceeds maximum limit
```

**Comment by saraedum** [comment]
Others had trouble with OSX here too: https://root.cern.ch/gitweb/?p=root.git;a=blob;f=bindings/pyroot/JupyROOT/handlers.py;h=32c38eb68c30aa9ec2cf9b2edbe7e15bb6971b3e#l98
But they don't explain why they exclude OSX here apparently.

**Comment by jdemeyer** [comment]
In any case, it's clear that this is a more general problem unrelated to cysignals.

**Comment by jdemeyer** [comment]
This seems to be a very very strange Python 3 + OS X bug. I didn't manage to find other reports of it so far.

**Comment by saraedum** [comment]
The commit message is not very helpful:
```
commit 598f938079cf6d21dee353e88001d06f02ca7298
Author: Danilo Piparo <danilo.piparo@cern.ch>
Date:   Tue Feb 16 22:14:07 2016 +0100

    Do not call setrlimit on osx
```

**Comment by saraedum** [comment]
So, @jdemeyer what do you propose? Should we just catch the exception if that call fails?

**Comment by jdemeyer** [comment]
https://github.com/sagemath/cysignals/tree/fix_osx_py3 (not tested yet)

**Comment by saraedum** [comment]
I see several reports of people struggling with OSX and setrlimit in general: 
```
      /* On some platforms, OPEN_MAX is the real limit, and getrlimit() is
       * full of nasty lies.  I'm looking at you, OSX 10.5.... */
```

**Comment by jdemeyer** [comment]
> I see several reports of people struggling with OSX and get/setrlimit in general:

Yes, but that is specifically for the number of open files (`RLIMIT_NOFILE`).

**Comment by saraedum** [comment]
The changes in https://github.com/sagemath/cysignals/commit/c4bff5e2b87b62220b17e2b7c38a0e2165986f32#commitcomment-27998445 fix this.

**Comment by jdemeyer** [comment]
I'll eventually make a new release, but there are some things that I would like to fix first.

**Comment by MMquant** [comment]
Guys I see that you were dealing with same problem as I do now. Problem is that `ulimit` cannot override settings in OS X kernel. So first you need to change limits stored in kernel and then you can use `ulimit` or `resource.setrlimit()` to manipulate limits.

**Example**

```
$ sysctl kern.maxfiles
kern.maxfiles: 12288
$ sysctl kern.maxfilesperproc
kern.maxfilesperproc: 10240
$ sudo sysctl -w kern.maxfiles=1048600
kern.maxfiles: 12288 -> 1048600
$ sudo sysctl -w kern.maxfilesperproc=1048576
kern.maxfilesperproc: 10240 -> 1048576
$ ulimit -S -n
256
$ ulimit -S -n 1048576
$ ulimit -S -n
1048576
```

after modifying kern files `resource.setrlimit()` works

**Comment by jdemeyer** [comment]
I don't see how this is related to the kernel limits...

Note that cysignals is only trying to *lower* the existing limit and in some strange cases that fails. Also, you don't explain why it works on Python 2 but not Python 3.
