### ISSUE TITLE
Why #include <Python.h>

### ISSUE THREAD

**Issue by jdemeyer** [sagemath/cysignals#8]
I don't see why you need `#include <Python.h>` in `implementation.c`. That's an include automatically added by Cython.

**Comment by malb** [comment]
Does it hurt? It makes my static checker happy.

**Comment by jdemeyer** [comment]
It doesn't hurt but it indicates that either your static checker or the way how you use it is broken.

**Comment by malb** [comment]
Since it doesn't hurt, I'll close this ticket. Feel free to reopen.
