### ISSUE TITLE
setup_requires=["Cython>=0.28b1"] wil install pre-release versions

### ISSUE THREAD

**Issue by isuruf** [sagemath/cysignals#81]
Even if there's a regular release like 0.28.1, it will install 0.28.2b1 if it existed.

**Comment by jdemeyer** [comment]
Thanks for telling me, but is this actually documented somewhere? I am having a hard time understanding how setuptools deals with versioning.

**Comment by isuruf** [comment]
https://pip.pypa.io/en/stable/reference/pip_install/#pre-release-versions

**Comment by jdemeyer** [comment]
OK thanks. By the way, this only affects master. The latest released version still works with older Cython versions.
