### ISSUE TITLE
`python setup.py install` with `cysignals` in `install_requires`

### ISSUE THREAD

**Issue by johnyf** [sagemath/cysignals#84]
I get the following error:

https://github.com/sagemath/cysignals/blob/db075e556b8b664690e73eae4b22b80be58064e0/setup.py#L142

In my case, the package that depends on `cysignals` builds extensions if optional arguments are given to its `setup.py`. These arguments cannot be passed via `pip`'s `--install-option`, because it (unintendedly) propagates them to dependencies, raising errors (https://github.com/pypa/pip/issues/1883).

So `python setup.py install` is the only option for installing from source (we could imagine `pip install .` first to get the dependencies including `cysignals`, then re-installing with `python setup.py install --foo`, but that is cumbersome).

Is there any way to have `python setup.py install` successfully install `cysignals` if it encounters it in `install_requires`?

(Assuming appropriate [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) are used, for example `'cysignals >= 1.7.0; platform_system = "Linux" or platform_system = "Darwin"'`.)

**Comment by jdemeyer** [comment]
Can you try instead `python setup.py install --old-and-unmanageable`? That might work.
