### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jdemeyer** [sagemath/cysignals#9]
[This documentation from Sage](http://doc.sagemath.org/html/en/developer/coding_in_cython.html#interrupt-and-signal-handling) should be moved here.

**Comment by malb** [comment]
I started in d2488a2cdd8e94bf3289e842ff1368ac0286eba3 but no clean up yet.

**Comment by jdemeyer** [comment]
I don't think this should be `README.rst`. We should have a simple `README.md` explaining basic usage and move the Sage documentation to a true manual. Eventually, we should also write documentation about `signals-CSI`.

Do you agree?

**Comment by malb** [comment]
- `.rst` vs. `.md` doesn't really make a difference to me, Python packages tend to use ReST, so I switched it over.
- I don't see a problem with the documentation being in `README.rst` but I have no preference either way.

**Comment by malb** [comment]
Closing this as done.
