### ISSUE TITLE
distutils.errors.DistutilsError ... [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by MrShamir** [sagemath/cysignals#93]
I encountered this problem while installing cysignals and cannot fix it. 
The error code is as following:
distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/79/9d/dea8c5181cdb77d32e20a44dd5346b0e4bac23c4858f2f66ad64bbcf4de8/Cython-0.28.2.tar.gz#sha256=634e2f10fc8d026c633cffacb45cd8f4582149fa68e1428124e762dbc566e68a: [Errno -2] Name or service not known

**Comment by jdemeyer** [comment]
The "download error" looks not related to cysignals at all.

**Comment by MrShamir** [comment]
Thank you very much.
